apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-helloworld 
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifest/
    repoURL: https://github.com/ahmed-gaal/python-helloworld 
    targetRevision: HEAD
  syncPolicy: {}
